hmrc/bitwarden-manager

- Dockerfile
fix module name typo in Dockerfile
> PSEC-1871-awslambdaric

- bitwarden_manager/clients/s3_client.py
- bitwarden_manager/export_vault.py
- poetry.lock
- pyproject.toml
- tests/bitwarden_manager/clients/test_s3_client.py
- tests/test_export_vault.py
* Pass new filename with iso timestamp
* Makes dating files easier and more readable
> PSEC-1897 refactor bitwarden vault export file names

- README.md
- bitwarden_manager/bitwarden_manager.py
- bitwarden_manager/clients/bitwarden_vault_client.py
- tests/bitwarden_manager/clients/stubs/bitwarden_client_stub.py
- tests/bitwarden_manager/clients/test_bitwarden_vault_client.py
- tests/bitwarden_manager/test_bitwarden_manager.py
* Add Bitwarden CLI timeout env var
* Add supplementary documentation
* To provide a method that allows fast increases in BW CLI timeout as we've seen issues
* Provide context & guidance on usage of such events/vars
> NOJIRA add CLI timeout env var

- Dockerfile
Ensure base libs are up to date
> Apt upgrade in docker image base

- bitwarden_manager/bitwarden_manager.py
- bitwarden_manager/clients/bitwarden_public_api.py
- bitwarden_manager/offboard_user.py
- tests/bitwarden_manager/clients/test_bitwarden_public_api.py
- tests/bitwarden_manager/resources/get_members.json
- tests/test_app.py
- tests/test_offboard_user.py
Add remove_user event
This change support offboarding of a user from bitwarden org
> PSEC-1963-remove_user-event

- bitwarden_manager/bitwarden_manager.py
- tests/test_app.py
Bug
- Rerunning the lambda quickly failed due to "already logged in" errors 
More detail:
This fixes a bug in successive lambda runs failing due to disk persistence.
We were not always calling logout to cleanup encrypted app data on disk.
More more detail:
When an API call fails (due to timeout etc.) the data remains in place. This results in login falling on the next invocation login as we are "already logged in".
Why:
I think it's better to run a better cleanup here rather than ignoring "already logged in" errors so that app data is as fresh as possible to work on.
> Ensure we logout of bitwarden, even when an error has occurred

- docs/bitwarden-ump.md
> PSEC-1999-docs

- bitwarden_manager/clients/bitwarden_public_api.py
- tests/bitwarden_manager/clients/test_bitwarden_public_api.py
Fixed bug that double encoded externalId
> PSEC-1962-fix-double-encoding

- bitwarden_manager/temp/role_updater.py
Task currently times out in dev (lambda has timeout set to 2 mins). So adding some logging to see how far it gets.
> Add logging

- bitwarden_manager/clients/bitwarden_public_api.py
- tests/bitwarden_manager/clients/test_bitwarden_public_api.py
- Revert "PSEC-2029 update test endpoints to Bitwarden EU servers"
- Revert "PSEC-2029 Switching over to Bitwarden EU servers"
> PSEC 2029 migrate to eu revert back

- bitwarden_manager/clients/bitwarden_public_api.py
- bitwarden_manager/clients/user_management_api.py
- bitwarden_manager/onboard_user.py
- tests/bitwarden_manager/clients/test_bitwarden_public_api.py
- tests/bitwarden_manager/clients/test_user_management_api.py
- tests/bitwarden_manager/test_onboard_user.py
Use derived custom group ids when computing the list of groups to associate a user with
> PSEC-2059-custom-groups

- bitwarden_manager/temp/list_collection_items.py
- tests/bitwarden_manager/temp/stubs/bitwarden_client_stub.py
- tests/bitwarden_manager/temp/stubs/list_collections.json
- tests/bitwarden_manager/temp/test_list_collection_items.py
Update list_collection_items event to require collection_name instead of collection_id
> PSEC-1993-list_collection_items_given_collection_name

- bitwarden_manager/bitwarden_manager.py
- tests/bitwarden_manager/temp/test_list_collection_items.py
Event routing for list_collection_items event added
> PSEC-1993-list_collection_items_routing

- bitwarden_manager/temp/list_collection_items.py
- tests/bitwarden_manager/temp/stubs/list_collections.json
- tests/bitwarden_manager/temp/test_list_collection_items.py
Troubleshooting list_collection_items event failure
> PSEC-1993-list_collection_troubleshoot

- bitwarden_manager/temp/list_collection_items.py
- tests/bitwarden_manager/temp/stubs/bitwarden_client_stub.py
Troubleshooting list_collection_items event failure
Fixed CLI command
> PSEC-1993-troubleshoot_list_collection_items

- bitwarden_manager/clients/bitwarden_vault_client.py
- bitwarden_manager/temp/list_collection_items.py
Typo fix and more error logging
> PSEC-1993-typo-fix

- bitwarden_manager/temp/list_collection_items.py
- tests/bitwarden_manager/temp/test_list_collection_items.py
> PSEC-1993-print

- Dockerfile
- bitwarden_manager/clients/bitwarden_vault_client.py
- tests/bitwarden_manager/clients/stubs/bitwarden_client_failing_authentication_stub.py
- tests/bitwarden_manager/clients/stubs/bitwarden_client_failing_config_server_stub.py
- tests/bitwarden_manager/clients/stubs/bitwarden_client_failing_operations_stub.py
- tests/bitwarden_manager/clients/stubs/bitwarden_client_stub.py
- tests/bitwarden_manager/clients/test_bitwarden_vault_client.py
- tests/bitwarden_manager/conftest.py
- tests/bitwarden_manager/temp/stubs/bitwarden_client_stub.py
Configure Bitwarden server URI
> PSEC-2117-bitwarden-migration

- bitwarden_manager/bitwarden_manager.py
> PSEC-2117-fix-bw-cli-path

- README.md
- bitwarden_manager/clients/bitwarden_public_api.py
- bitwarden_manager/clients/bitwarden_vault_client.py
- bitwarden_manager/temp/list_custom_groups.py
- tests/bitwarden_manager/clients/test_bitwarden_public_api.py
- tests/bitwarden_manager/clients/test_bitwarden_vault_client.py
- tests/bitwarden_manager/temp/test_list_custom_groups.py
This reverts commit 0db42b16ed57a49534b51710282051f84ee55ad6.
> Revert "PSEC-2117 back to the US Org"

- README.md
- bitwarden_manager/clients/bitwarden_public_api.py
- bitwarden_manager/clients/bitwarden_vault_client.py
- bitwarden_manager/temp/list_custom_groups.py
- tests/bitwarden_manager/clients/test_bitwarden_public_api.py
- tests/bitwarden_manager/clients/test_bitwarden_vault_client.py
- tests/bitwarden_manager/temp/test_list_custom_groups.py
This reverts commit 9001c1a0799936538893b7b02a85f3cf85c8ce4f.
> Reapply "PSEC-2117 back to the US Org"

- README.md
- bitwarden_manager/clients/bitwarden_public_api.py
- bitwarden_manager/clients/bitwarden_vault_client.py
- bitwarden_manager/temp/list_custom_groups.py
- tests/bitwarden_manager/clients/test_bitwarden_public_api.py
- tests/bitwarden_manager/clients/test_bitwarden_vault_client.py
- tests/bitwarden_manager/temp/test_list_custom_groups.py
This reverts commit a987a45dab7375e048f85c194b2963381aa3292c.
> Revert "Reapply "PSEC-2117 back to the US Org""

- bitwarden_manager/bitwarden_manager.py
- bitwarden_manager/clients/s3_client.py
- bitwarden_manager/temp/update_collection_external_ids.py
- tests/bitwarden_manager/clients/test_s3_client.py
- tests/bitwarden_manager/temp/data_export.json
- tests/bitwarden_manager/temp/test_list_collection_items.py
- tests/bitwarden_manager/temp/test_update_collection_external_ids.py
Update collection external IDs from data export file re: Bitwarden EU migration
> PSEC-2126-update-collection-external-ids

- bitwarden_manager/reinvite_users.py
- tests/bitwarden_manager/test_reinvite_users.py
> BAU-update-max-reinvites

- bitwarden_manager/clients/bitwarden_public_api.py
> PSEC-2207-log-message

- bitwarden_manager/bitwarden_manager.py
- bitwarden_manager/clients/bitwarden_vault_client.py
- poetry.lock
- pyproject.toml
Added extra logging to help narrow down where CLI errors are coming from.
> PSEC-2279 Extra logging

- bitwarden_manager/clients/dynamodb_client.py
- tests/bitwarden_manager/clients/test_dynamodb_client.py
Bug fix to ensure total_invites has a default value returned
> PSEC-2326-bug-fix

- bitwarden_manager/bitwarden_manager.py
- tests/bitwarden_manager/test_bitwarden_manager.py
Log a warning when BitwardenUserAlreadyExistsException is raised - to avoid pagerduty alerting on failed lambda function execution for it
> PSEC-2331-handle-useralreadyexists-error
